name: Release
on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true
      - run: vp build --mode prod
      - name: Validate version
        id: validate
        run: |
          vp exec node ./tool/validate_ci.ts
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: ${{ steps.validate.outputs.prerelease == 'true' }}
          working_directory: dist
          files: |
            main.js
            manifest.json
            styles.css
